version: '3.8'

services:
  cache-x-001:
    build:
      context: .
      dockerfile: ./_infrastructure/Dockerfile
    ports: 
      - "3200:3200"
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development